### ISSUE TITLE
Error : as sphinx extension.

### ISSUE THREAD

**Issue by amsitlab** [uyar/pygenstub#3]
I has adding 'pygenstub' to [project-rootdir]/docs/source/conf.py of spinx , and error show when i type `make html` on [project-rootdir]/docs/ and it is contents of error log file generated by sphinx:

`# Sphinx version: 2.1.2
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   Running Sphinx v2.1.2
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 3 source files that are out of date
#   updating environment:
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] index
#   reading sources... [ 66%] microot
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.1.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   pygenstub (1.4.0) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/pygenstub.py
#   sphinx.ext.todo (2.1.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (2.1.2) from /data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 150, in run
    documenter.generate(more_content=self.content)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 757, in generate
    self.add_content(more_content)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 495, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 463, in process_doc
    self.options, docstringlines)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/application.py", line 449, in emit
    return self.events.emit(event, *args)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pygenstub.py", line 813, in process_docstring
    signature = extract_signature("\n".join(lines))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pygenstub.py", line 109, in extract_signature
    root = publish_doctree(docstring, settings_overrides={"report_level": 5})
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/core.py", line 481, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/domains/__init__.py", line 269, in run
    return super().run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/domains/python.py", line 743, in run
    domain = cast(PythonDomain, self.env.get_domain('py'))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sphinx/util/docutils.py", line 377, in env
    return self.state.document.settings.env
AttributeError: 'Values' object has no attribute 'env'`

**Comment by uyar** [comment]
On a first simple check, I couldn't reproduce it but I'll look into it further.
